[pytest]
addopts =
    -vs
    ; --headed
    --output=output/playwright
   --screenshot=on
   --video=on
;    --tracing=on
    --alluredir=output/report/allure_results
    --clean-alluredir

disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
;filterwarnings =
;    ignore::Warning
