name: 学习我的第一个CI


# .github/workflows 目录下的每一个 .yaml 文件都是一个独立的、并行的“监听器”。 
# 哪个文件会运行，完全取决于你在文件顶部定义的 on:（触发事件）。

# 触发条件：当推送到 main 分支时触发
on:
  push:
    branches: [ "main" ]

jobs:
  say-hello:
    # 使用免费额度最高的 Linux 运行环境
    runs-on: ubuntu-latest

    steps:
    # 步骤 1：拉取仓库代码
    - name: Checkout code
      uses: actions/checkout@v6

    # 步骤 2：打印一句欢迎语
    - name: Run a one-line script
      run: echo "Hello, GitHub Actions! 我的 CI 已经成功运行了！"

    # 步骤 3：查看当前环境的 Python 版本（Linux 默认自带 Python）
    - name: Check Python Version
      run: python3 --version